name: TO_RELEASE_MINOR
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          npm install
      - name: Init git identity
        run: |
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git config --global user.name "${{ secrets.MY_NAME }}"
      - name: Release minor
        run: |
          npm run release:minor
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push new tag
        run: |
          git push --follow-tags origin master
      - name: Build lib
        run: |
          npm run build:lib
      - name: Publish lib on NPM registry
        run: |
          npm publish dist/angular-page-visibility-ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
